spring:
  datasource:
    url: jdbc:postgresql://buildyourtrip-postgres-itineraries.buildyourtrip.svc.cluster.local:5432/buildyourtrip
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /api/v1

ai:
  service:
    url: http://buildyourtrip-ai-service.buildyourtrip.svc.cluster.local:8085

maps:
  service:
    url: http://buildyourtrip-maps-service.buildyourtrip.svc.cluster.local:8086
    api-key: ${GOOGLE_MAPS_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

logging:
  level:
    root: INFO
    it.buildyourtrip.itineraries: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO 