spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8082
  servlet:
    context-path: /api/v1

ai:
  service:
    url: ${AI_SERVICE_URL}

maps:
  service:
    url: ${MAPS_SERVICE_URL}
    api-key: ${GOOGLE_MAPS_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  health:
    db:
      enabled: true

logging:
  level:
    root: WARN
    it.buildyourtrip.itineraries: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN 