spring:
  datasource:
    url: jdbc:postgresql://buildyourtrip-postgres-itineraries.buildyourtrip.svc.cluster.local:5432/buildyourtrip
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

server:
  port: 8082

ai:
  service:
    url: http://buildyourtrip-ai-service.buildyourtrip.svc.cluster.local:8085

maps:
  service:
    url: http://buildyourtrip-maps-service.buildyourtrip.svc.cluster.local:8086
    api-key: ${GOOGLE_MAPS_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  health:
    db:
      enabled: true

logging:
  level:
    root: WARN
    it.buildyourtrip.itineraries: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN 