spring:
  application:
    name: itineraries-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /api/v1

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8085}

logging:
  level:
    root: INFO
    com.buildyourtrip: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

services:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

spring.jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  time-zone: UTC
  serialization:
    write-dates-as-timestamps: false 