apiVersion: v1
kind: ConfigMap
metadata:
  name: itineraries-service-config-prod
  namespace: buildyourtrip-prod
data:
  application.yml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: false

    ai:
      service:
        url: ${AI_SERVICE_URL}

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: never
      health:
        db:
          enabled: true

    logging:
      level:
        com.buildyourtrip.itineraries: WARN
        org.springframework.web: WARN
        org.hibernate.SQL: WARN 