apiVersion: v1
kind: ConfigMap
metadata:
  name: itineraries-service-config-dev
  namespace: buildyourtrip-dev
data:
  application.yml: |
    server:
      port: 8082
      servlet:
        context-path: /api/v1

    spring:
      datasource:
        url: jdbc:postgresql://postgres-itineraries:5432/buildyourtrip
        username: postgres
        password: postgres
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

    ai:
      service:
        url: http://ai-service:8085

    maps:
      service:
        url: http://maps-service:8086
        api-key: ${GOOGLE_MAPS_API_KEY}

    management:
      endpoint:
        health:
          show-details: always

    logging:
      level:
        com.buildyourtrip.itineraries: INFO
        org.springframework.web: INFO
        org.hibernate.SQL: INFO 