apiVersion: v1
kind: Secret
metadata:
  name: itineraries-secrets
  namespace: buildyourtrip
type: Opaque
data:
  db-url: aHR0cHM6Ly9wb3N0Z3Jlcy5idWlsZHlvdXJ0cmlwLmNvbS9pdGluZXJhcmllc19kYg==  # https://postgres.buildyourtrip.com/itineraries_db
  db-username: cG9zdGdyZXM=  # postgres
  db-password: cG9zdGdyZXM=  # postgres 