apiVersion: v1
kind: Service
metadata:
  name: itineraries-service
  namespace: buildyourtrip
spec:
  selector:
    app: itineraries-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP 